  

spring: 
  datasource:
    password: masterkey
    url: jdbc:mysql://localhost:3306/digitaldbcore?createDatabaseIfNotExist=true
    username: root
  h2:
    console:
      settings:
        trace:  true  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  application:
    name: digitalapi